name: AmbulanceGameEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - joblib
  - folium
  - requests
  - pandas
  - matplotlib
  - seaborn
  - python-dotenv
  - pytest
  - pytest-cov
  - lightgbm
  - scikit-learn  
  - pip
  - pip:
    - polyline
    - here-polyline-converter
    - git+https://github.com/gerritgr/SimpleOSMRenderer.git
