name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: AmbulanceGameEnv
          environment-file: environment.yml
          python-version: 3.11
          auto-activate-base: false

      - name: Run tests
        shell: bash -l {0}
        run: |
            source $CONDA/etc/profile.d/conda.sh
            conda activate AmbulanceGameEnv
            pip install pytest
            PYTHONPATH=. pytest
