name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: AmbulanceGameEnv
          environment-file: environment.yml
          python-version: 3.11
          auto-activate-base: false

      - name: Run tests with coverage
        shell: bash -l {0}
        run: |
          conda activate AmbulanceGameEnv
          pip install pytest-cov codecov
          PYTHONPATH=. pytest --cov=. --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
